package com.example.ui.settings

enum class SettingsScreen {
    ONBOARDING,
    HOME,
    THEME_LIBRARY,
    CUSTOM_THEME_STUDIO,
    KEYBOARD_PREFS,
    CUSTOMIZE_KEYS,
    TYPING_PREFS,
    SOUND_HAPTIC,
    DICTIONARY,
    SHORTCUTS,
    CLIPBOARD,
    VAULT,
    TYPING_ANALYTICS,
    BACKUP_RESTORE,
    SYSTEM_DIAGNOSTICS,
    PRIVACY,
    ABOUT
}

